import { Lang, TranslationSet } from "./types";

export const SCRIPT_URL = 'https://script.google.com/macros/s/AKfycbzQg1tkrETgB3t0b612vPH2T2OPA4StImyMam1ALNv-Lu188i8r9lLvSScJgcszNEYAcw/exec';

export const TRANSLATIONS: Record<Lang, TranslationSet> = {
  RU: {
    title: "Мониторинг Склада", progress: "ОБЩИЙ ПРОГРЕСС", next: "СЛЕДУЮЩИЙ", list: "АКТИВНЫЕ",
    lunch: "ОБЕД", victory: "ПЛАН ВЫПОЛНЕН!",
    status_active: "В РАБОТЕ", status_pause: "ПАУЗА", status_wait: "ОЖИДАНИЕ",
    eta_prefix: "ЧЕРЕЗ: ", delay_prefix: "ОПОЗДАНИЕ: ",
    lbl_start: "НАЧАЛО", lbl_dur: "В РАБОТЕ",
    stats_title: "СТАТИСТИКА", stat_done: "ГОТОВО", stat_queue: "ОЧЕРЕДЬ",
    list_done: "ВЫГРУЖЕНО", list_wait: "В ОЧЕРЕДИ",
    drv_title: "Терминал", btn_login: "Войти", btn_start: "НАЧАТЬ", btn_finish: "ЗАВЕРШИТЬ",
    lbl_photo1: "Общее фото (Сзади)", lbl_photo2: "Фото пломбы", lbl_photo_empty: "Фото пустого",
    msg_uploading: "Загрузка...", msg_success: "Успешно!",
    login_title: "Вход", reg_title: "Регистрация", empty: "Нет задач",
    btn_reg: "Отправить", btn_cancel: "Отмена",
    issue_title: "Сообщить о проблеме", issue_desc_ph: "Опишите проблему...", issue_btn: "Отправить проблему", issue_upload: "Добавить фото", issue_success: "Проблема отправлена",
    btn_history: "История проблем", history_title: "История", history_empty: "Проблем не найдено", history_back: "Назад к списку",
    
    menu_history: "История",
    menu_logout: "Выйти",
    lbl_description: "Описание",
    lbl_photos_list: "Фотографии",
    btn_open_drive: "Открыть оригинал",
    msg_loading_history: "Загрузка истории...",
    
    nav_dashboard: "Дашборд",
    nav_history: "Архив",
    nav_plan: "Поставки",
    nav_downtime: "Простои",
    nav_analytics: "Аналитика",
    
    tv_mode: "ТВ",
    tv_exit: "Выйти",
    
    search_placeholder: "Поиск по ID контейнера...",
    export_csv: "Экспорт CSV",
    
    analytics_title: "Аналитика за 7 дней",
    analytics_week: "Неделя",
    analytics_avg_time: "Среднее время (мин)",
    analytics_containers: "Контейнеров",
    analytics_no_data: "Нет данных за этот период",
    
    log_title: "План поставок",
    log_date: "Дата поставки",
    log_add_row: "Добавить контейнер",
    log_submit: "Создать план",
    log_success: "План успешно создан",
    log_lot: "Lot No",
    log_ws: "W/S",
    log_pallets: "Паллеты/Кейсы",
    log_phone: "Телефон водителя",
    log_eta: "ETA",
    log_id: "Container ID",
    
    log_mode_create: "Новый план",
    log_mode_edit: "Управление планом",
    log_edit_title: "Редактирование",
    log_btn_edit: "Изменить",
    log_btn_save: "Сохранить",
    log_no_data: "План на эту дату пуст",
    
    hist_select_date: "Выберите дату",
    hist_load: "Загрузить",
    hist_no_data: "Нет данных за эту дату",
    
    dtl_operator: "Оператор",
    dtl_zone: "Зона",
    dtl_photos: "Фотоотчет",
    
    // ✅ NEW: AGRL Role Translations
    nav_arrival: "Прибытие",
    nav_arrival_analytics: "Аналитика прибытий",
    
    arrival_terminal_title: "Терминал отметки прибытия",
    arrival_mark: "Отметить прибытие",
    arrival_time: "Время прибытия",
    arrival_set_time: "Установить время",
    arrival_current_time: "Текущее время",
    arrival_manual_time: "Ввести вручную",
    arrival_success: "Прибытие зафиксировано",
    arrival_reset: "Сбросить",
    arrival_not_marked: "Не отмечено",
    arrival_marked: "Прибыл в",
    arrival_on_site: "На территории",
    arrival_waiting_unload: "Ожидает выгрузки",
    
    analytics_arrival_title: "Аналитика простоев",
    analytics_date_from: "С",
    analytics_date_to: "По",
    analytics_load_data: "Загрузить",
    analytics_total_downtime: "Общий простой",
    analytics_avg_downtime: "Средний простой",
    analytics_records_count: "Записей",
    analytics_minutes: "мин",
    analytics_hours: "ч",
    analytics_col_date: "Дата",
    analytics_col_eta: "План",
    analytics_col_arrival: "Прибытие",
    analytics_col_end: "Окончание",
    analytics_col_downtime: "Простой",
    analytics_edit_arrival: "Изменить прибытие",
    analytics_no_arrivals: "Нет данных о прибытиях за выбранный период"
  },
  EN_CN: {
    title: "Warehouse Monitor / 仓库监控", progress: "PROGRESS / 进度", next: "NEXT / 下一个", list: "ACTIVE TASKS / 任务",
    lunch: "LUNCH BREAK / 午休", victory: "COMPLETED! / 完成",
    status_active: "ACTIVE / 运行", status_pause: "PAUSED / 暂停", status_wait: "WAITING / 等待",
    eta_prefix: "ETA / 预计: ", delay_prefix: "DELAY / 延迟: ",
    lbl_start: "START / 开始", lbl_dur: "DURATION / 持续",
    stats_title: "STATISTICS / 统计", stat_done: "DONE / 完成", stat_queue: "QUEUE / 排队",
    list_done: "UNLOADED / 已卸载", list_wait: "QUEUE / 等待中",
    drv_title: "Terminal / 终端", btn_login: "Login / 登录", btn_start: "START / 开始", btn_finish: "FINISH / 完成",
    lbl_photo1: "General Photo / 照片", lbl_photo2: "Seal Photo / 封条", lbl_photo_empty: "Empty Photo / 空箱",
    msg_uploading: "Uploading... / 上传中", msg_success: "Success! / 成功",
    login_title: "Login / 登录", reg_title: "Register / 注册", empty: "No tasks / 无任务",
    btn_reg: "Send / 发送", btn_cancel: "Cancel / 取消",
    issue_title: "Report Issue / 报告问题", issue_desc_ph: "Describe the issue... / 描述问题", issue_btn: "Submit Issue / 提交", issue_upload: "Add Photo / 添加照片", issue_success: "Report sent / 发送成功",
    btn_history: "Issue History / 问题记录", history_title: "History / 历史", history_empty: "No issues found / 无记录", history_back: "Back / 返回",

    menu_history: "History / 历史",
    menu_logout: "Logout / 退出",
    lbl_description: "Description / 描述",
    lbl_photos_list: "Photos / 照片",
    btn_open_drive: "Open Original / 打开原图",
    msg_loading_history: "Loading history... / 加载历史...",
    
    nav_dashboard: "Dashboard / 仪表板",
    nav_history: "Archive / 档案",
    nav_plan: "Logistics / 物流",
    nav_downtime: "Downtime / 停机",
    nav_analytics: "Analytics / 分析",
    
    tv_mode: "TV",
    tv_exit: "Exit",
    
    search_placeholder: "Search by Container ID...",
    export_csv: "Export CSV",
    
    analytics_title: "Analytics (7 days) / 分析 (7天)",
    analytics_week: "Week / 周",
    analytics_avg_time: "Avg time (min) / 平均时间",
    analytics_containers: "Containers / 集装箱",
    analytics_no_data: "No data for this period / 无数据",
    
    log_title: "Delivery Plan / 交付计划",
    log_date: "Delivery Date / 交货日期",
    log_add_row: "Add Container / 添加集装箱",
    log_submit: "Create Plan / 创建计划",
    log_success: "Plan Created / 计划已创建",
    log_lot: "Lot No",
    log_ws: "W/S",
    log_pallets: "Pallets/Cases",
    log_phone: "Driver Phone",
    log_eta: "ETA",
    log_id: "Container ID",
    
    log_mode_create: "New Plan / 新计划",
    log_mode_edit: "Manage Plan / 管理计划",
    log_edit_title: "Edit / 编辑",
    log_btn_edit: "Edit / 修改",
    log_btn_save: "Save / 保存",
    log_no_data: "No plan for this date / 无计划",
    
    hist_select_date: "Select Date / 选择日期",
    hist_load: "Load / 加载",
    hist_no_data: "No data for this date / 无数据",
    
    dtl_operator: "Operator / 操作员",
    dtl_zone: "Zone / 区域",
    dtl_photos: "Report Photos / 报告照片",
    
    // ✅ NEW: AGRL Role Translations
    nav_arrival: "Arrival / 到达",
    nav_arrival_analytics: "Arrival Analytics / 到达分析",
    
    arrival_terminal_title: "Arrival Terminal / 到达终端",
    arrival_mark: "Mark Arrival / 标记到达",
    arrival_time: "Arrival Time / 到达时间",
    arrival_set_time: "Set Time / 设置时间",
    arrival_current_time: "Current Time / 当前时间",
    arrival_manual_time: "Enter Manually / 手动输入",
    arrival_success: "Arrival Recorded / 到达已记录",
    arrival_reset: "Reset / 重置",
    arrival_not_marked: "Not Marked / 未标记",
    arrival_marked: "Arrived at / 到达于",
    arrival_on_site: "On Site / 在场",
    arrival_waiting_unload: "Waiting Unload / 等待卸货",
    
    analytics_arrival_title: "Downtime Analytics / 停机分析",
    analytics_date_from: "From / 从",
    analytics_date_to: "To / 到",
    analytics_load_data: "Load / 加载",
    analytics_total_downtime: "Total Downtime / 总停机时间",
    analytics_avg_downtime: "Avg Downtime / 平均停机",
    analytics_records_count: "Records / 记录",
    analytics_minutes: "min / 分钟",
    analytics_hours: "h / 小时",
    analytics_col_date: "Date / 日期",
    analytics_col_eta: "ETA / 预计",
    analytics_col_arrival: "Arrival / 到达",
    analytics_col_end: "End / 结束",
    analytics_col_downtime: "Downtime / 停机",
    analytics_edit_arrival: "Edit Arrival / 编辑到达",
    analytics_no_arrivals: "No arrival data for selected period / 所选期间无到达数据"
  }
};
