import { Lang, TranslationSet } from "./types";

export const SCRIPT_URL = 'https://script.google.com/macros/s/AKfycbyr93urmvnJiYcDR0CcML92KR9dS0pAN8qdrI-wK9p1q8Z3Hn3JqkH1MRo4LgYtOy4QeA/exec';

export const TRANSLATIONS: Record<Lang, TranslationSet> = {
  RU: {
    title: "Мониторинг Склада", progress: "ОБЩИЙ ПРОГРЕСС", next: "СЛЕДУЮЩИЙ", list: "АКТИВНЫЕ",
    lunch: "ОБЕД", victory: "ПЛАН ВЫПОЛНЕН!",
    status_active: "В РАБОТЕ", status_pause: "ПАУЗА", status_wait: "ОЖИДАНИЕ",
    eta_prefix: "ЧЕРЕЗ: ", delay_prefix: "ОПОЗДАНИЕ: ",
    lbl_start: "НАЧАЛО", lbl_dur: "В РАБОТЕ",
    stats_title: "СТАТИСТИКА", stat_done: "ГОТОВО", stat_queue: "ОЧЕРЕДЬ",
    list_done: "ВЫГРУЖЕНО", list_wait: "В ОЧЕРЕДИ",
    drv_title: "Терминал", btn_login: "Войти", btn_start: "НАЧАТЬ", btn_finish: "ЗАВЕРШИТЬ",
    lbl_photo1: "Общее фото (Сзади)", lbl_photo2: "Фото пломбы", lbl_photo_empty: "Фото пустого",
    msg_uploading: "Загрузка...", msg_success: "Успешно!",
    login_title: "Вход", reg_title: "Регистрация", empty: "Нет задач",
    btn_reg: "Отправить", btn_cancel: "Отмена",
    issue_title: "Сообщить о проблеме", issue_desc_ph: "Опишите проблему...", issue_btn: "Отправить проблему", issue_upload: "Добавить фото", issue_success: "Проблема отправлена",
    btn_history: "История проблем", history_title: "История", history_empty: "Проблем не найдено", history_back: "Назад к списку",
    
    menu_history: "История",
    menu_logout: "Выйти",
    lbl_description: "Описание",
    lbl_photos_list: "Фотографии",
    btn_open_drive: "Открыть оригинал",
    msg_loading_history: "Загрузка истории...",
    
    nav_dashboard: "Дашборд",
    nav_history: "Архив",
    nav_plan: "Поставки",
    nav_downtime: "Простои", // НОВОЕ
    
    log_title: "План поставок",
    log_date: "Дата поставки",
    log_add_row: "Добавить контейнер",
    log_submit: "Создать план",
    log_success: "План успешно создан",
    log_lot: "Lot No",
    log_ws: "W/S",
    log_pallets: "Паллеты/Кейсы",
    log_phone: "Телефон водителя",
    log_eta: "ETA",
    log_id: "Container ID",
    
    log_mode_create: "Новый план",
    log_mode_edit: "Управление планом",
    log_edit_title: "Редактирование",
    log_btn_edit: "Изменить",
    log_btn_save: "Сохранить",
    log_no_data: "План на эту дату пуст",
    
    hist_select_date: "Выберите дату",
    hist_load: "Загрузить",
    hist_no_data: "Нет данных за эту дату",
    
    dtl_operator: "Оператор",
    dtl_zone: "Зона",
    dtl_photos: "Фотоотчет",

    nav_arrival: "Время простоя",
    arr_title: "Аналитика простоя машин",
    arr_avg_wait: "Среднее ожидание",
    arr_max_wait: "Макс. ожидание",
    arr_vehicles_total: "Всего машин",
    arr_no_data: "Нет данных за эту дату",
    arr_col_container: "Контейнер",
    arr_col_ws: "W/S",
    arr_col_eta: "ETA",
    arr_col_arrival: "Прибытие на АГМ",
    arr_col_unload_start: "Начало разгрузки",
    arr_col_wait: "Простой",
    arr_col_zone: "Зона",
    arr_col_operator: "Оператор",
    arr_status_ok: "Норма",
    arr_status_warn: "Задержка",
    arr_status_crit: "Критично",
    arr_no_arrival: "Нет данных",
    arr_vehicles_with_data: "с данными о прибытии",
    arr_over_hour: "простой > 1 часа",

    shift_morning: "Утренняя смена",
    shift_evening: "Вечерняя смена",
    shift_norm: "НОРМА",
    shift_ahead: "опережение",
    shift_behind: "отставание",
    shift_on_track: "в графике",
  },
  EN_CN: {
    title: "Warehouse Monitor / 仓库监控", progress: "PROGRESS / 进度", next: "NEXT / 下一个", list: "ACTIVE TASKS / 任务",
    lunch: "LUNCH BREAK / 午休", victory: "COMPLETED! / 完成",
    status_active: "ACTIVE / 运行", status_pause: "PAUSED / 暂停", status_wait: "WAITING / 等待",
    eta_prefix: "ETA / 预计: ", delay_prefix: "DELAY / 延迟: ",
    lbl_start: "START / 开始", lbl_dur: "DURATION / 持续",
    stats_title: "STATISTICS / 统计", stat_done: "DONE / 完成", stat_queue: "QUEUE / 排队",
    list_done: "UNLOADED / 已卸载", list_wait: "QUEUE / 等待中",
    drv_title: "Terminal / 终端", btn_login: "Login / 登录", btn_start: "START / 开始", btn_finish: "FINISH / 完成",
    lbl_photo1: "General Photo / 照片", lbl_photo2: "Seal Photo / 封条", lbl_photo_empty: "Empty Photo / 空箱",
    msg_uploading: "Uploading... / 上传中", msg_success: "Success! / 成功",
    login_title: "Login / 登录", reg_title: "Register / 注册", empty: "No tasks / 无任务",
    btn_reg: "Send / 发送", btn_cancel: "Cancel / 取消",
    issue_title: "Report Issue / 报告问题", issue_desc_ph: "Describe the issue... / 描述问题", issue_btn: "Submit Issue / 提交", issue_upload: "Add Photo / 添加照片", issue_success: "Report sent / 发送成功",
    btn_history: "Issue History / 问题记录", history_title: "History / 历史", history_empty: "No issues found / 无记录", history_back: "Back / 返回",

    menu_history: "History / 历史",
    menu_logout: "Logout / 退出",
    lbl_description: "Description / 描述",
    lbl_photos_list: "Photos / 照片",
    btn_open_drive: "Open Original / 打开原图",
    msg_loading_history: "Loading history... / 加载历史...",
    
    nav_dashboard: "Dashboard / 仪表板",
    nav_history: "Archive / 档案",
    nav_plan: "Logistics / 物流",
    nav_downtime: "Downtime / 停机", // НОВОЕ
    
    log_title: "Delivery Plan / 交付计划",
    log_date: "Delivery Date / 交货日期",
    log_add_row: "Add Container / 添加集装箱",
    log_submit: "Create Plan / 创建计划",
    log_success: "Plan Created / 计划已创建",
    log_lot: "Lot No",
    log_ws: "W/S",
    log_pallets: "Pallets/Cases",
    log_phone: "Driver Phone",
    log_eta: "ETA",
    log_id: "Container ID",
    
    log_mode_create: "New Plan / 新计划",
    log_mode_edit: "Manage Plan / 管理计划",
    log_edit_title: "Edit / 编辑",
    log_btn_edit: "Edit / 修改",
    log_btn_save: "Save / 保存",
    log_no_data: "No plan for this date / 无计划",
    
    hist_select_date: "Select Date / 选择日期",
    hist_load: "Load / 加载",
    hist_no_data: "No data for this date / 无数据",
    
    dtl_operator: "Operator / 操作员",
    dtl_zone: "Zone / 区域",
    dtl_photos: "Report Photos / 报告照片",

    nav_arrival: "Wait Time / 等待时间",
    arr_title: "Vehicle Wait Time Analytics / 车辆等待分析",
    arr_avg_wait: "Avg Wait / 平均等待",
    arr_max_wait: "Max Wait / 最大等待",
    arr_vehicles_total: "Total Vehicles / 总车辆",
    arr_no_data: "No data for this date / 无数据",
    arr_col_container: "Container / 集装箱",
    arr_col_ws: "W/S",
    arr_col_eta: "ETA",
    arr_col_arrival: "Arrival at AGM / 到达时间",
    arr_col_unload_start: "Unload Start / 开始卸货",
    arr_col_wait: "Wait / 等待",
    arr_col_zone: "Zone / 区域",
    arr_col_operator: "Operator / 操作员",
    arr_status_ok: "OK / 正常",
    arr_status_warn: "Delay / 延迟",
    arr_status_crit: "Critical / 严重",
    arr_no_arrival: "No data / 无数据",
    arr_vehicles_with_data: "with arrival data / 有到达数据",
    arr_over_hour: "wait > 1 hour / 等待超1小时",

    shift_morning: "Morning Shift / 早班",
    shift_evening: "Evening Shift / 晚班",
    shift_norm: "NORM / 标准",
    shift_ahead: "ahead / 提前",
    shift_behind: "behind / 落后",
    shift_on_track: "on track / 正常",
  }
};
